### ISSUE TITLE
MacOS Sonoma. 

### ISSUE THREAD

**Issue by DC4114** [taarkov/Honor-MagicBook-X15-Hackintosh#14]
Is there a chance that you will update the efi to support sonama?

**Comment by taarkov** [comment]
This EFI is up-to-date but i did not try it on Sonoma. Sonoma has to get a few more updates to be stable on Mac and Hacks. You can try if you want. If you already tried and got error/issue, specify it.

**Comment by DC4114** [comment]
I've tried sonama, the issues is after the device wakes up from sleep, the brightness goes really low and can't control the brightness with keyboard nor from the panel. BUT, after 2-3 minutes the the screen goes black. closing the lid and opening it fixes it (temporary fix). I thought it might be the an issue related with backlight, so I tried manually patching SSDT-PNLF, but that did not fix it.

**Comment by taarkov** [comment]
You can try adding GPRW-PATCH.ssdt to your ACPI folder and Config.plist. Let me know the updates.

https://github.com/dortania/OpenCore-Post-Install/blob/master/extra-files/GPRW-Patch.plist

**Comment by DC4114** [comment]
I'm not sure what GPRW-PATCH.ssdt is, but I've added GPRW.plist to config.plist that didn't fix the issue. Another thing I've noticed it, the bug doesn't exist while the device is charging.

**Comment by taarkov** [comment]
You can learn what GPRW and GPRW-PATCH is. You don't need to add GPRW.plist(?). There is already GPRW.ssdt on EFI. Anyway, i already give ya the tip.

**Comment by DC4114** [comment]
![Screenshot](https://github.com/taarkov/Honor-MagicBook-X15-Hackintosh/assets/75291323/784bff12-d9ac-4a48-b413-7a65efcb7f44)
I've added this to ACPI>patch, it is from the link you've provided. Is there a guide where I can learn about GPRW-PATCH? Thannks.

**Comment by taarkov** [comment]
Just type SSDT/DSDT's name and you can find out what is that for. Is this method fix your problem?

**Comment by DC4114** [comment]
no that did not fix the issue.

**Comment by taarkov** [comment]
Try disabling RTC wake scheduling. Kernel>Patch. Manually add and enable or just enable.

**Comment by DC4114** [comment]
that didn't work either.

**Comment by taarkov** [comment]
What changes have you done with the EFI to be exact?

**Comment by DC4114** [comment]
https://drive.google.com/file/d/1vfb-2QlnGqRjRArEUQJsxbfiuta4Kkl8/view?usp=drive_link
here is the modified EFI i'm using.

**Comment by taarkov** [comment]
Keep using GPRW-Patch.SSDT and also re-adjust and use UTBMap.

**Comment by taarkov** [comment]
@DC4114 hi again. I had free time so i look into this situation. GPRW-Patch, PLUG and manually patching PNLF is useless. Just enable RTC patch on Kernel>Patch or manually add Patch&RTC sections into your plist. Also checkout keyboard wake issue on Dortania's Guide. Disable fTPM and WOL on BIOS and WOL on PowerNap.

**Comment by DC4114** [comment]
there is no option in the bios to disable WOL. also I've added rtc patch plist to config.plist, that didn't seem to fix the issue as well. I'll look into keyboard wake issues later, rn I'm very busy with studies(sorry).

**Comment by taarkov** [comment]
WOL is Wake on LAN but do not turn it off because it disabled Wi-Fi both macOS and Windows. Just disable WOL at PowerNap on macOS.

**Comment by DC4114** [comment]
powernap is disabled on macos (pmset powernap 0)

**Comment by taarkov** [comment]
You didn't have to disable PowerNap, just the Wake on LAN feature on the PowerNap pal...

**Comment by DC4114** [comment]
how to disable just WAL in PowerNap? 
settings >battery>option> wake on network is disabled.

**Comment by DC4114** [comment]
Finally fixed it by adding SSDT-LID-after-wake.aml and this patch to ACPI>Patch. 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<dict>
		<key>Base</key>
		<string></string>
		<key>BaseSkip</key>
		<integer>0</integer>
		<key>Comment</key>
		<string>change _LID to XLID</string>
		<key>Count</key>
		<integer>0</integer>
		<key>Enabled</key>
		<true/>
		<key>Find</key>
		<data>X0xJRAA=</data>
		<key>Limit</key>
		<integer>0</integer>
		<key>Mask</key>
		<data></data>
		<key>OemTableId</key>
		<data></data>
		<key>Replace</key>
		<data>WExJRAA=</data>
		<key>ReplaceMask</key>
		<data></data>
		<key>Skip</key>
		<integer>0</integer>
		<key>TableLength</key>
		<integer>0</integer>
		<key>TableSignature</key>
		<data>RFNEVA==</data>
	</dict>
</array>
</plist>

after doing this there was display blinking issue, solved it by framebuffer patching. 
( https://www.tonymacx86.com/threads/blinking-screen-after-wake-intel-hd-520.305798/ )
