### ISSUE TITLE
it just stops

### ISSUE THREAD

**Issue by ivanushka123amongus** [taarkov/Honor-MagicBook-X15-Hackintosh#16]
![20240404_230847317 (1)](https://github.com/taarkov/Honor-MagicBook-X15-Hackintosh/assets/113372058/03404266-81da-4764-a384-595af23bce9b)
I don't know how to fix it (catalina) heeeelp

**Comment by taarkov** [comment]
Hello friend. Could you try to change default SMBIOS on config.plist which is MacBookPro16,3 to MacBookPro16,1 with using GenSMBIOS. After changing it, boot OpenCore and try Reset NRAM then try to Install macOS. 
+++
You could easily install macOS Monterey+. Why did you prefer macOS Catalina, that version of macOS is kind of outdate nowadays.

**Comment by ivanushka123amongus** [comment]
Okay. I tried Monterey, but i ran into a new problem https://ds-blobs-3.cdn.devapps.ru/30504047/20240405_213146249.jpg?s=00a9fd8553d9c9a86611476500000000d3b4696166428a26a453199bdbc1477a
https://ds-blobs-1.cdn.devapps.ru/30504046/20240405_213031925.jpg?s=00a9fd8553d9c9a86611478500000000acea46e33b678bf3c2e2d7810eca85d6
i'm really waiting for your answer!

**Comment by taarkov** [comment]
Try with another USB port or try disabling USBMap & UTBMap kexts on config.plist.

**Comment by ivanushka123amongus** [comment]
I tried to find USBMap, but i found only UTBMap. Another USB port didn't work, kexts too. But, But, BUT i found (maybe) something interesting. If you turn off SSDT-EC-USBX-LAPTOP.aml it will continue to start, but IT'S LIKE MY FLASH DRIVE IS USB 0.1. it still stuck

**Comment by taarkov** [comment]
Couldn't you find atleast USB 2.0 flash drive sth?

**Comment by ivanushka123amongus** [comment]
i have only 3.0

**Comment by taarkov** [comment]
I meant your flash drive, not your USB port.

**Comment by ivanushka123amongus** [comment]
no, i'm really. Idon't have USB 2.0 flash drives(

**Comment by ivanushka123amongus** [comment]
OK. I found my oldest 2.0 flash drive and installed opencore on it...it didnt worked

**Comment by ivanushka123amongus** [comment]
I tried online method (with basesystem.dmg) and IT STARTED..but it wants **internet** connection, but there is _no_ wifi configurator. Can you link the image it worked with?
(im in russia)

**Comment by taarkov** [comment]
> OK, OK, OK..? I tried online method (with basesystem.dmg) and IT STARTED..but it wants **internet** connection, but there is _no_ wifi configurator. Can you link the image it worked with? (im in russia)

Привет, брат. Я из Турции и буду рад помочь в вашем вопросе. Я использовал файл изображения с нашего сайта. Это автономный файл изображения, поэтому вам не потребуется подключение к Интернету в процессе установки. Я использую переводчик, чтобы вы лучше понимали друг друга. Вы можете использовать эту ссылку:

[Here is Yandex Link for Sonoma 14.4 image file](https://disk.yandex.com/d/V2HBod0kqR--7w?ref=blog.yusufklncc.com.tr)
Use Win32 Disk Imager for writing image file to the USB.

**Comment by ivanushka123amongus** [comment]
Thank you! But I dont have much time now, to try it. My honor burned his usb ports, so I can try it..maybe next week. Thank you again

**Comment by ivanushka123amongus** [comment]
Okay, so i tried your image, and it ACTUALLY tried to install this!
but it rebooted when estimating time was like 12-10 mins. And then it just bootlooping......
WHAT DID I DO WRONG😢



P.S. I burn the image with Balena Etcher

**Comment by ivanushka123amongus** [comment]
![Uploading 9262516C-46BF-486B-889E-772F38FD0066.png…]()

**Comment by ivanushka123amongus** [comment]
I EVEN ASKED ABOUT MY PROBLEM ON 4PDA, AND NO ONE WAS ABLE TO SOLVE MY PROBLEM.. but is there still something left that I can try..?
I tried installing Sonoma, I tried Monterey, I tried Ventura, and the problem is same. But, Is there can be problems, with for example my SSD, or my RAM? And I see, that our specs are actually not the same
You have 2x4 Micron DDR4 Memory, but I have Samsung 2x4 DDR4 Memory. You have [i dont know the name of your SSD], I have WDC PC SN730 SDPBNTY-512G-1036 SSD. And I think the real problem is that I have Intel(R) UHD Graphics, and you Intel(R) UHD Graphics 630, And I Don't Know, if This can be somehow prevent macos from the installing. But I have the last idea. Can you try to dump the whole mac os directory to raw image, for me, to try burning this image on my drive. I don't have any more ideas to try. Btw device number of my video graphics is PCI\VEN_8086&DEV_9B41&SUBSYS_125D152D&REV_02
Waiting for your answer, Thanks!

**Comment by ivanushka123amongus** [comment]
Holy freak, I FINALLY INSTALED IT! And all the problem was in the one config line - SecureBootModel, and all what i needed is to switch it from Default to Disabled. At first I installed Monterey, but then switched to Sonoma. IT WORKS BEAUTIFUL!! And by the way, I updated all kexts and the opencore, and idk why, but facetime, iMessage and some other Apple ID Features don't work with AirPortItlwm.kext, to get them to work, you just need to switch to itlwm.kext and Heliport. Other features, like touchpad or camera are working just fine. **only thing thats the sleep dont working** I changed layout-id to 15 because our sound carts are not the same. Here is the new updated EFI so you can use it, or upload on the release tab! (may..bee..pls)
https://drive.google.com/file/d/1DbSnTJ_XE1tjOMgFcm0AfNhO5AU9Xjtv/view
And the last question is...how to install sequoia? I tried it already from https://yusufklncc.com.tr/ but it didnt work, i cant say you whats the reason because i think error happens in debug really fast
AND THE LAST THING: It wont boot with any other images of macOS, only yusuf.
